##########################################
# ------------ Sand Stacking ----------- #
##########################################

### Make falling blocks land on various types of blocks.
Falling Blocks Land:
  Enabled: true
  Upon Blocks:
  - enchantment_table
  - bed_block
  - chest
  - trapped_chest
  - ender_chest
  - sand
# List of blocks here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

### Let falling blocks stack upon the void.
### This may be useful to make raidable factions in The End.
Void Stacking: true

### Tired of stacking just a few sand blocks at a time?
### Makes it easier to stack multiple blocks at once.
Better Stacking: true


### Don't touch this
Config Version: 1